### PR TITLE
add optional instrumenter argument

### PR DESCRIPTION
**Pull request by sethpollack**
For example I would like to be able to pass the [isparta](https://github.com/douglasduteil/isparta) instrumenter as an option.

### CODE REVIEW

**Comment by sethpollack** [comment]
Thanks!

**Comment by sethpollack** [comment]
Would you mind updating on NPM as well? Thanks for the quick pull!

**Comment by taichi** [comment]
release done.

**Comment by sethpollack** [comment]
Thanks!

**Pull request merged**
